
package com.stacs.cs5031.p3.client.gui;

import javax.swing.*;
import java.awt.Color;
import com.stacs.cs5031.p3.client.gui.helper_classes.CustomFontLoader;
import com.stacs.cs5031.p3.client.gui.helper_classes.OnClickEventHelper;
import com.stacs.cs5031.p3.client.gui.helper_classes.RoundedBorder;

/**
 * This class is responsible for creating the main page of the organiser.
 * Part of this code (i.e basic element layout code) was generated by GUI Builder, "Window Builder for
 * JavaFx/Swing" extension in vscode.
 */
public class OrganiserHomePage {
  public static void main(String[] args) {

    int organiserId = 1; // For testing purposes, you can hardcode the organiserId

    createPage(organiserId);

  }


  /**
   * This is the constructor of the OrganiserHomePage class.
   * @param organiserId
   */
  public OrganiserHomePage(int organiserId) {
    if (organiserId <=0) {
       System.out.println("Please provide a valid organiser id.");
     return;
    }
    createPage(organiserId);
   
  }

  /**
   * This method is responsible  for creating the main page of the organiser.
   * @param organiserId - the id of the organiser
   */
  public static void createPage(int organiserId) {
    JFrame frame = new JFrame("Organiser Home");
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setSize(896, 483);

    frame.setLocationRelativeTo(null);

    JPanel panel = new JPanel();
    panel.setLayout(null);
    panel.setBackground(Color.decode("#f4c064"));
    PageElements pageEl = new PageElements(organiserId, panel, frame);
    pageEl.addAllElements();

    frame.add(panel);
    frame.setVisible(true);

  }

  

    /**
   * This class is responsible for creating the elements of the create booking
   * page.
   * It contains methods to create and add the elements to the panel.
   */
  public static class PageElements {
    private int organiserId; //id of the organiser
    private JPanel panel; // The panel to which the elements will be added
    private JFrame frame; // The frame to which the panel will be added

    /**
     * This is the constructor of the PageElements class.
     * 
     * @param panel       - the panel to which the elements will be added
     * @param organiserId - the id of the organiser
     * @param frame       - the frame to which the panel will be added
     */
    public PageElements(int organiserId, JPanel panel, JFrame frame) {
      this.panel = panel;
      this.organiserId = organiserId;
      this.frame = frame;
      // getRooms();
    }

    /**
     * This button is responsible for adding all elements to the page.
     */
    public void addAllElements() {
      addViewBookingsButton();
      addCreateBookingButton();
      addOrganiserHomeLbl();
    }

    /**
     * This method is responsible adding the view booking button to the screen.
     * 
     */
    private void addViewBookingsButton() {

      JButton viewBookingsBtn = new JButton("View Bookings");
      viewBookingsBtn.setBounds(276, 267, 314, 40);
      viewBookingsBtn.setBackground(Color.decode("#bca8e4"));
      viewBookingsBtn.setForeground(Color.decode("#000"));
      viewBookingsBtn.setFont(CustomFontLoader.loadFont("./resources/fonts/Lexend.ttf", 14));
      viewBookingsBtn.setBorder(new RoundedBorder(4, Color.decode("#3d364a"), 1));
      viewBookingsBtn.setFocusPainted(false);
      OnClickEventHelper.setOnClickColor(viewBookingsBtn, Color.decode("#7c6f97"), Color.decode("#bca8e4"));
      panel.add(viewBookingsBtn);

    }

    /**
     * This method is responsible for adding the create booking button to the screen.
     */
    private void addCreateBookingButton() {

      JButton createBookingBtn = new JButton("Create New Booking");
      createBookingBtn.setBounds(282, 176, 315, 40);
      createBookingBtn.setBackground(Color.decode("#bca8e4"));
      createBookingBtn.setForeground(Color.decode("#000"));
      createBookingBtn.setFont(CustomFontLoader.loadFont("./resources/fonts/Lexend.ttf", 14));
      createBookingBtn.setBorder(new RoundedBorder(4, Color.decode("#3d364a"), 1));
      createBookingBtn.setFocusPainted(false);
      OnClickEventHelper.setOnClickColor(createBookingBtn, Color.decode("#7c6f97"), Color.decode("#bca8e4"));

      createBookingBtn.addActionListener(e -> {
        new CreateBookingPage(organiserId);
        frame.dispose();
      });
      panel.add(createBookingBtn);

    }

    /**
     * This method is used to add the Organiser Home Label at the top of the screen.
     */
    private void addOrganiserHomeLbl() {
      JLabel element3 = new JLabel("Organiser Home");
      element3.setBounds(275, 65, 401, 78);
      element3.setFont(CustomFontLoader.loadFont("./resources/fonts/Lexend.ttf", 40));
      element3.setForeground(Color.decode("#000"));
      panel.add(element3);
    }
  }

}